---
platform: linux
image_resource:
    type: docker-image
    source:
      repository: maven
      tag: 3.6.3-ibmjava-8-alpine
inputs:
- name: source-code
outputs:
- name: test-results
params:
  mvn_args: ""
run: 
    path: sh
    args:
    - -exec
    - |
        ls
        cd source-code
        if[$mvn_args != ""]; then
            mvn $mvn_args
        fi