---
platform: linux
image_resource:
    type: docker-image
    source:
      repository: maven
      tag: 3.6.3-ibmjava-8-alpine

inputs:
- name: source-code

outputs:
- name: test-results

run: 
    path: sh
    args:
    - -exec
    - |
        ls
        cd source-code
        mvn test